# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

#python env関数

# 仮想環境一覧
function listenvs() {
    echo "📁 ローカル仮想環境:"
    if [ -d . ]; then
        for d in */; do
            if [ -f "$d/Scripts/activate" ] || [ -f "$d/bin/activate" ]; then
                echo "  - ${d%/}"
            fi
        done
    fi

    echo "🌐 グローバル仮想環境（~/venvs）:"
    if [ -d "$HOME/venvs" ]; then
        for d in "$HOME/venvs"/*; do
            if [ -f "$d/Scripts/activate" ] || [ -f "$d/bin/activate" ]; then
                echo "  - $(basename "$d")"
            fi
        done
    else
        echo "  (~/venvs ディレクトリが存在しません)"
    fi
}

# 仮想環境有効化
function actenv() {
    local name="$1"
    local local_path="./$name/Scripts/activate"
    local global_path="$HOME/venvs/$name/Scripts/activate"

    if [ -f "$local_path" ]; then
        source "$local_path"
        echo "✅ Activated (local): $name"
    elif [ -f "$global_path" ]; then
        source "$global_path"
        echo "✅ Activated (global): $name"
    else
        echo "❌ No such virtual environment: $name (searched in ./ and ~/venvs)"
    fi
}

# 仮想環境無効化
function deactenv() {
    if declare -f deactivate > /dev/null; then
        deactivate
        echo "🔻 Deactivated"
    else
        echo "⚠️  No environment is active"
    fi
}

# 仮想環境作成
function createenv() {
    local mode="$1"
    local name="$2"

    if [ -z "$mode" ] || [ -z "$name" ]; then
        echo "❗使い方: createenv [loc|glo] env_name"
        return 1
    fi

    local target_path=""
    if [ "$mode" == "loc" ]; then
        target_path="./$name"
    elif [ "$mode" == "glo" ]; then
        target_path="$HOME/venvs/$name"
    else
        echo "❗モードは 'loc' または 'glo' を指定してください"
        return 1
    fi

    python -m venv "$target_path"
    echo "🎉 Created $name at $target_path"
}

# 仮想環境削除
function deleteenv() {
    local mode="$1"
    local name="$2"

    if [ -z "$mode" ] || [ -z "$name" ]; then
        echo "❗使い方: deleteenv [loc|glo] env_name"
        return 1
    fi

    local target_path=""
    if [ "$mode" == "loc" ]; then
        target_path="./$name"
    elif [ "$mode" == "glo" ]; then
        target_path="$HOME/venvs/$name"
    else
        echo "❗モードは 'loc' または 'glo' を指定してください"
        return 1
    fi

    if [ ! -d "$target_path" ]; then
        echo "❌ 仮想環境が見つかりません: $target_path"
        return 1
    fi

    # 確認プロンプト
    read -p "⚠️ 本当に削除しますか？ '$target_path' (y/n): " confirm
    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
        rm -rf "$target_path"
        echo "🗑️  削除しました: $target_path"
    else
        echo "🚫 削除をキャンセルしました"
    fi
}
